Github actions: better handling for incompatible storm/stormpy versions

diff --git a/.github/workflows/buildtest.yml b/.github/workflows/buildtest.yml
--- a/.github/workflows/buildtest.yml
+++ b/.github/workflows/buildtest.yml
@@ -40,7 +40,6 @@ jobs:
         debugOrRelease: ["debug", "release"]
 
     # Allow failures of stable versions as new features might have been added
-    continue-on-error: true
     steps:
       - name: Setup environment variables
         # this is strangely the best way to implement environment variables based on the value of another
@@ -78,9 +77,22 @@ jobs:
         run: |
           sudo docker exec storm bash -c "cd /opt; source venv/bin/activate; cd /opt/pycarl; python setup.py build_ext $DEBUG_SWITCH -j ${NR_JOBS} develop"
       - name: Build stormpy
+        id: build_stormpy
+        shell: bash {0} // Deactivate fast-fail to handle exit code for incompatibility
         run: |
           sudo docker exec storm bash -c "cd /opt; source venv/bin/activate; cd /opt/stormpy; python setup.py build_ext --storm-dir /opt/storm/build/ $DEBUG_SWITCH -j ${NR_JOBS} develop"
+          status=$?
+          if [ $status -eq 42 ]; then
+            # Warn about incompatibility but do not handle as failure
+            echo "::warning file=setup.py,line=82::Stormpy is incompatible with stable version of Storm"
+            # Deactivate tests
+            echo "::set-output name=run_tests::false"
+          else
+            echo "::set-output name=run_tests::true"
+            exit $status
+          fi
       - name: Run tests
+        if: steps.build_stormpy.outputs.run_tests == 'true'
         run: |
           # Install dependencies for tests
           # numpy is used in sphinx tests
