Wheel tests for macOS

diff --git a/.github/workflows/wheelpypi.yml b/.github/workflows/wheelpypi.yml
--- a/.github/workflows/wheelpypi.yml
+++ b/.github/workflows/wheelpypi.yml
@@ -33,7 +33,6 @@ jobs:
             runs-on: macos-14 # macos-14+ (including latest) are ARM64 runners
             xcode: 15.3
       fail-fast: false
-
     steps:
       - uses: actions/checkout@v4
       - uses: maxim-lobanov/setup-xcode@v1
@@ -51,6 +50,7 @@ jobs:
           name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
           path: ./wheelhouse/*.whl
 
+
   build_sdist:
     name: Build source distribution
     runs-on: ubuntu-latest
@@ -63,8 +63,9 @@ jobs:
           name: cibw-sdist
           path: dist/*.tar.gz
 
+
   test_wheels_linux:
-    name: Test wheels on different Linux distros
+    name: Test wheel on ${{ matrix.distro }}
     needs: [build_wheels]
     runs-on: ubuntu-latest
     strategy:
@@ -72,7 +73,7 @@ jobs:
       matrix:
         distro:
           - ubuntu:24.04
-          - debian:bookworm
+          - debian:12
           - fedora:latest
           - archlinux:latest
     steps:
@@ -81,7 +82,13 @@ jobs:
           pattern: cibw-wheels-linux-intel-*
           path: dist
           merge-multiple: true
-      - name: Run test in ${{ matrix.distro }}
+      - name: Checkout test files
+        uses: actions/checkout@v4
+        with:
+          path: dist/test_files
+          sparse-checkout: |
+            tests
+      - name: Install from wheel and test
         run: |
           docker run -i --rm -v ./dist:/wheel ${{ matrix.distro }} /bin/bash << 'EOF'
           set -euo pipefail
@@ -117,10 +124,82 @@ jobs:
 
           # Run a basic import test (replace with pytest if needed)
           python3 -c "import stormpy; print('Import successful')"
+          pip install pytest nbval numpy
+          pytest test_files/tests
           EOF
 
+
+  test_wheels_mac:
+    name: Test wheel on ${{ matrix.distro.name }}
+    needs: [build_wheels]
+    runs-on: ${{ matrix.distro.distro }}
+    strategy:
+      fail-fast: false
+      matrix:
+        distro:
+          - {name: "XCode 14.3, Intel",
+             os: macos-intel,
+             distro: "macos-13",
+             xcode: "14.3"
+          }
+          - {name: "XCode 15.4, ARM",
+             os: macos-arm,
+             distro: "macos-14",
+             xcode: "15.4"
+          }
+          - {name: "XCode 16.3, ARM",
+             os: macos-arm,
+             distro: "macos-15",
+             xcode: "16.3"
+          }
+    steps:
+      - uses: maxim-lobanov/setup-xcode@v1
+        with:
+          xcode-version: ${{ matrix.distro.xcode }}
+      - uses: actions/download-artifact@v4
+        with:
+          pattern: cibw-wheels-${{ matrix.distro.os }}-*
+          path: dist
+          merge-multiple: true
+      - name: Install dependencies
+        # cmake and gmp and python3 are already installed
+        run: |
+          brew update
+          brew install automake boost cln ginac glpk hwloc xerces-c z3
+      - name: Install from wheel and test
+        working-directory: dist
+        run: |
+          # Get major+minor version (e.g. "311" for Python 3.11)
+          PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}{sys.version_info.minor}')")
+          echo "Python version: $PY_VER"
+          # Look for a matching wheel in the current directory
+          WHEEL=$(ls stormpy-*-cp${PY_VER}-*.whl 2>/dev/null | head -n1 || true)
+          echo "Found wheel: $WHEEL"
+          if [ -z "$WHEEL" ]; then
+            echo "Error: No stormpy wheel found for Python ${PY_VER:0:1}.${PY_VER:1}." >&2
+            exit 1
+          fi
+          echo "Installing $WHEEL..."
+          python3 -m venv venv
+          source venv/bin/activate
+          python3 -m pip install "$WHEEL"
+      - name: Checkout test files
+        uses: actions/checkout@v4
+        with:
+          path: dist/test_files
+          sparse-checkout: |
+            tests
+      - name: Test
+        working-directory: dist
+        run: |
+          source venv/bin/activate
+          python3 -c "import stormpy; print('Import successful')"
+          python3 -m pip install pytest nbval numpy
+          pytest test_files/tests
+
+
   upload_pypi:
-    needs: [build_wheels, build_sdist, test_wheels_linux]
+    needs: [build_wheels, build_sdist, test_wheels_linux, test_wheels_mac]
     runs-on: ubuntu-latest
     environment: pypi
     permissions:
